name: Deploy to production site.
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
    - uses: actions/checkout@master
    - name: Install PHP dependencies
      run: composer install
    - name: Upload to giathuoctot
      run: rsync -razhe "ssh -o StrictHostKeyChecking=no" --exclude={'.git','.github','.gitignore','composer.json'} . ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }}:/var/www/giathuoctot.vn/public/wp-content/plugins/giathuoctotshop/
    - name: Upload to giathuochapu
      run: rsync -razhe "ssh -o StrictHostKeyChecking=no" --exclude={'.git','.github','.gitignore','composer.json'} . ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }}:/var/www/giathuochapu.com/public/wp-content/plugins/gtt-shop/
